name: Build QMK Firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile QMK Firmware
      uses: qmk/qmk-action@v1
      with:
        working-dir: firmware/hackropad
        keyboard: hackropad
        keymap: default

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: "*.uf2"
